language: perl

perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

install:
    - dzil authordeps --missing | cpanm
    - dzil listdeps --author --missing | cpanm

# Allow Travis to use Docker
sudo: false

script:
    - dzil test --author --release
